- name: Copy "{{component}}" service file
  ansible.builtin.copy:
    src: "{{component}}.service.j2"
    dest: "/etc/systemd/system/{{component}}.service"

- name: Daemon reload service
  ansible.builtin.systemd_service:
    daemon_reload: true    

- name: Enable and Start the "{{component}}"
  ansible.builtin.systemd_service:
    name: "{{component}}"
    enabled: yes
    state: restarted